config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord 
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def new 
        @book = Book.new
    end
    
    def create
        @book = Book.new(book_params)
        if @book.save
            redirect_to book_path(@book.id), notice: 'Book was successfully created.'
        else
            @books = Book.all.order(created_at: :desc)
            render :index
        end
    end
    
    def index
        @books = Book.all
        @book = Book.new
    end
    
    def show
        @book = Book.find(params[:id])
    end
    
    def edit
        @book = Book.find(params[:id])
    end
  
    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            redirect_to book_path(@book.id), notice: 'Book was successfully updated.' 
        else
            render :edit
        end
    end
    
    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to '/books'
    end
    
    private
    
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
    <div class="edit_book">
        <%= form_with model: @book do |f| %>
        
            <% if @book.errors.any? %>
                <div id="error_explanation">
                    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
                    <ul>
                        <%  @book.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                </div>
            <% end %>
        
            <div class="field">
                <%= f.label :title, "Title" %>
                <%=f.text_field :title %>
            </div>
            <div class="field">
                <%= f.label :body, "Body" %>
                <%=f.text_area :body %>
            </div>
            <div class="submit">
                <%= f.submit '  Update Book  ' %>
            </div>
        <% end %>
    </div>
    <br>
    <%= link_to'Show', book_path(@book.id) %> | 
    <%= link_to'Back', books_path %>
    

app/views/books/index.html.erb
<body>
  
  <h1>Books</h1>
  <table>
    
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <% @books.each do |book| %>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to'Show', book_path(book.id) %></td>
        <td><%= link_to'Edit', edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
        </tr>
        <% end %>
    </tbody>
  </table>

  <h2>New book</h2>
    <div class="new_book">
      <%= form_with model: @book, url: '/books', method: :post do |f| %>

        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
              <ul>
                <%  @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
          </div>
        <% end %>
      
      <div class="field">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :body, "Body" %>
        <%= f.text_area :body %>
      </div>
      <div class="submit">
        <%= f.submit '  Create Book  ' %>
        </div>
      <% end %>
    </div>
</body>

app/views/books/show.html.erb
<div class="show-book">
    <strong>Title:</strong> <p><%= @book.title %></p>
</div>
<div class="show-book">
    <strong>Body:</strong> <p><%= @book.body %></p>
</div>

<%= link_to'Edit', edit_book_path(@book.id) %> | 
<%= link_to'Back', books_path %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>Bookers</title>
    </head>
    <body>
        <h1 class="header-line">ようこそ <strong>Bookers</strong> へ！</h1>
        <main>
            <p class="text"><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
            <p class="text">印象を共有し交換することができます</p>
            <!--<a class="text link" href="index.html">start</a>-->
            <p class="text link">
                <%= link_to'start', '/books', class: "nav-link" %>
            </p>
        </main>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>